/**
 * Generates 150 mock transactions and writes them to backend/data/transactions.js.
 * Run with: node backend/scripts/generateTransactions.js
 */

const fs = require('fs');
const path = require('path');
const paymentMethods = require('../data/paymentMethods');

// ── Helpers ───────────────────────────────────────────────────────────────────

function pick(arr) {
  return arr[Math.floor(Math.random() * arr.length)];
}

function randBetween(min, max) {
  return Math.random() * (max - min) + min;
}

function randInt(min, max) {
  return Math.floor(randBetween(min, max + 1));
}

// Weighted random: weights array must match items array length
function weightedPick(items, weights) {
  const total = weights.reduce((a, b) => a + b, 0);
  let threshold = Math.random() * total;
  for (let i = 0; i < items.length; i++) {
    threshold -= weights[i];
    if (threshold <= 0) return items[i];
  }
  return items[items.length - 1];
}

function randomTimestamp(daysBack = 90) {
  const now = Date.now();
  const past = now - daysBack * 24 * 60 * 60 * 1000;
  return new Date(randBetween(past, now)).toISOString();
}

// ── Country → currency map ────────────────────────────────────────────────────

const countryCurrency = {
  KE: 'KES', TZ: 'TZS', UG: 'UGX', RW: 'RWF', MZ: 'MZN',
  GH: 'GHS', CM: 'XAF', CI: 'XOF', ZM: 'ZMW',
  US: 'USD', GB: 'GBP', CA: 'CAD', AU: 'AUD', NZ: 'NZD',
  DE: 'EUR', FR: 'EUR', ES: 'EUR', IT: 'EUR', NL: 'EUR',
  BE: 'EUR', AT: 'EUR', PT: 'EUR', FI: 'EUR', IE: 'EUR',
  SE: 'SEK', DK: 'DKK', NO: 'NOK',
  BR: 'BRL', MX: 'MXN', AR: 'ARS',
  IN: 'INR', JP: 'JPY', CN: 'CNY', HK: 'HKD', MO: 'MOP',
  SG: 'SGD', MY: 'MYR', TH: 'THB', PH: 'PHP',
  NG: 'NGN', ZA: 'ZAR', AE: 'AED',
};

// ── Volume weights per method (simulates real-world adoption) ─────────────────
// Higher weight = more transactions generated for that method
const methodWeights = {
  visa:        20,
  mastercard:  18,
  paypal:      15,
  pix:         14,
  mpesa:       12,
  apple_pay:   10,
  klarna:       8,
  sepa:         8,
  afterpay:     7,
  alipay:       7,
  mtn_momo:     6,
  oxxo:         5,
};

// ── Amount distribution by method type ───────────────────────────────────────
// Returns a realistic USD amount respecting the method's min/max
function generateAmount(method) {
  const { minAmount, maxAmount, type } = method;
  // Use a skewed distribution: most transactions cluster at the lower end
  const skewFactor = {
    mobile_money:    0.15,
    card:            0.30,
    bnpl:            0.50,
    bank_transfer:   0.60,
    digital_wallet:  0.25,
    instant_payment: 0.20,
    cash_voucher:    0.10,
  }[type] || 0.25;

  const raw = minAmount + Math.pow(Math.random(), 1 - skewFactor) * (maxAmount - minAmount);
  return parseFloat(raw.toFixed(2));
}

// ── Device type ───────────────────────────────────────────────────────────────
function generateDeviceType(method) {
  if (method.popularOnMobile) {
    return weightedPick(['mobile', 'desktop', 'tablet'], [65, 25, 10]);
  }
  return weightedPick(['mobile', 'desktop', 'tablet'], [30, 60, 10]);
}

// ── Status (driven by authRate) ───────────────────────────────────────────────
function generateStatus(method) {
  const r = Math.random();
  if (r < method.authRate) return 'success';
  // Failed vs pending: ~80/20 split among non-success
  return Math.random() < 0.8 ? 'failed' : 'pending';
}

// ── Generate transactions ─────────────────────────────────────────────────────

const methodsById = Object.fromEntries(paymentMethods.map(m => [m.id, m]));
const methodIds   = paymentMethods.map(m => m.id);
const weights     = methodIds.map(id => methodWeights[id] || 5);

const transactions = Array.from({ length: 150 }, (_, i) => {
  const methodId = weightedPick(methodIds, weights);
  const method   = methodsById[methodId];
  const country  = pick(method.countries);
  const currency = countryCurrency[country] || method.currencies[0];

  return {
    id:        `txn_${String(i + 1).padStart(4, '0')}`,
    methodId,
    country,
    currency,
    amountUSD: generateAmount(method),
    deviceType: generateDeviceType(method),
    status:    generateStatus(method),
    timestamp: randomTimestamp(90),
  };
});

// Sort chronologically so the data feels natural
transactions.sort((a, b) => new Date(a.timestamp) - new Date(b.timestamp));

// ── Write output ──────────────────────────────────────────────────────────────

const outPath = path.join(__dirname, '../data/transactions.js');
const content = `// Auto-generated by scripts/generateTransactions.js — do not edit by hand
const transactions = ${JSON.stringify(transactions, null, 2)};

module.exports = transactions;
`;

fs.writeFileSync(outPath, content, 'utf8');
console.log(`Written ${transactions.length} transactions to ${outPath}`);

// Quick sanity summary
const byStatus = transactions.reduce((a, t) => { a[t.status] = (a[t.status] || 0) + 1; return a; }, {});
const byType   = transactions.reduce((a, t) => {
  const type = methodsById[t.methodId].type;
  a[type] = (a[type] || 0) + 1;
  return a;
}, {});
console.log('Status distribution:', byStatus);
console.log('Type distribution:  ', byType);
